# This is a basic workflow to help you get started with Actions
name: Cloud Document Tool

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout working repository
        uses: actions/checkout@v2
    
      - name: Checkout system-connector-documentation-tool repository
        uses: actions/checkout@master
        with:
          repository: webMethods-Connectors/system-connector-documentation-tool
          token: ${{ secrets.GH_SECRET_TOKEN }}
          path: system-connector-documentation-tool
          ref: master
        
      - name: Run cloudDoc.jar
        run: |
          cd system-connector-documentation-tool/Documentation
          mkdir docs
          cd extras && mkdir html && cd ..
          java -cp "./build/cloudDoc.jar;./extras/libs/jsoup-1.6.0.jar/*" cloud_2.O.Convert ${{github.event.repository.name}}
        id: execute_Jar
          
      - name: Upload Generated Docs
        uses: actions/upload-artifact@v2
        with:
          name: Cloud Documentation
          path: |
            ./system-connector-documentation-tool/Documentation/docs/*